server:
  port: 8889
  servlet:
    context-path: /
spring:
#  mvc:
#    view:
#      prefix: /static/pages/
#      suffix: .html
  #    static-path-pattern: /static/**

  thymeleaf:
    mode: HTML
    prefix: classpath:/static/pages/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/jeecg-boot20200720?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      auto-mapping-behavior: full
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/**/*Mapper.xml
    type-aliases-package: com.helpjun.business.test
    global-config:
      # 逻辑删除配置
      db-config:
        # 删除前
        logic-not-delete-value: 1
        # 删除后
        logic-delete-value: 0
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.SQLiteDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
  redis:
    database: 0
    host: 192.168.1.211
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms




